[package]
name = "async-tls"
version = "0.1.0-alpha.0"
authors = ["quininer kel <quininer@live.com>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/quininer/async-tls"
homepage = "https://github.com/quininer/async-tls"
documentation = "https://docs.rs/async-tls"
readme = "README.md"
description = "Asynchronous TLS/SSL streams using Rustls."
categories = ["asynchronous", "cryptography", "network-programming"]
edition = "2018"

[badges]
travis-ci = { repository = "quininer/async-tls" }
appveyor = { repository = "quininer/async-tls" }

[dependencies]
smallvec = "0.6"
futures-preview = "0.3.0-alpha.17"
rustls = "0.15"
webpki = "0.19"

[features]
early-data = []

[dev-dependencies]
lazy_static = "1"
webpki-roots = "0.16"
async-std = { path = "../async-std" }
