[package]
name = "server"
version = "0.5.0"
authors = ["The async-rs developers", "quininer <quininer@live.com>"]
edition = "2018"

[dependencies]
structopt = "0.2"
async-std = "0.99"
async-tls = { path = "../.." }
rustls = "0.16"
webpki = "0.21"
