[package]
name = "client"
version = "0.1.0"
authors = ["quininer <quininer@live.com>"]
edition = "2018"

[dependencies]
async-std = { path = "../../../async-std" }
structopt = "0.2"
async-tls = { path = "../.." }
