[package]
name = "client"
version = "0.1.0"
authors = ["quininer <quininer@live.com>"]
edition = "2018"

[dependencies]
futures-preview = "0.3.0-alpha.17"
async-std = { path = "../../../async-std" }
structopt = "0.2"
tokio-rustls = { path = "../.." }
webpki-roots = "0.16"
