[package]
name = "client"
version = "0.1.0"
authors = ["quininer <quininer@live.com>"]
edition = "2018"

[dependencies]
structopt = "0.2"
rustls    = "0.16"
async-std = "0.99"
async-tls = { path = "../.." }
